# -*- coding: utf-8 -*-
"""pickle_testing_file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E07pwtlAhXd5RcUgf1SKIWAbAVmvk36x
"""

import pandas as pd
import numpy as np
import pickle
from sklearn.linear_model import LinearRegression

# Load the model from the pickle file
model_filename = 'Linear_Regression.pkl'
with open(model_filename, 'rb') as file:
    loaded_model = pickle.load(file)

# Example new testing data
new_data = pd.DataFrame({
    'TV': [100, 200, 300]  # Replace with your actual values
})

# Convert to NumPy array
new_data_np = new_data.values

# Check the shape
print("New data shape:", new_data_np.shape)

# Ensure it has the correct dimensions for predictions
if new_data_np.ndim == 1:
    new_data_expanded = new_data_np[:, np.newaxis]  # Reshape if it’s 1D
else:
    new_data_expanded = new_data_np  # Use as is if already 2D

# Making predictions on the new testing data
new_predictions = loaded_model.predict(new_data_expanded)

# Display the predictions
print("Predictions for the new data:", new_predictions)

